apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
commonLabels:
  environment: dev
namespace: label-bot-dev
resources:
- certificate.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml