apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-github-app
spec:
  replicas: 9
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ml-app-inference-secret
              key: DATABASE_URL
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: ml-app-inference-secret
              key: WEBHOOK_SECRET
        # The values for the Kubeflow issue-label-bot application
        # that is available in the GitHub marketplace      
        - name: APP_ID
          value: "27079"
        # Pato the GitHub app PEM key
        - name: GITHUB_APP_PEM_KEY
          value: /var/secrets/github/kf-label-bot-prod.private-key.pem
        # The GCP project and pubsub topic to publish to should
        # correspond to the production backend. The project is unfortunately
        # named issue-label-bot-dev.
        - name: GCP_PROJECT_ID
          value: issue-label-bot-dev
        - name: GCP_PUBSUB_TOPIC_NAME
          value: event_queue
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/user-gcp-sa.json        
        - name: FLASK_ENV
          value: production
  